# Generated by Django 3.2.9 on 2022-01-19 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('emp_id', models.IntegerField(max_length=10)),
                ('phone_num', models.IntegerField(max_length=10)),
                ('salary', models.IntegerField(max_length=10)),
            ],
        ),
    ]
