# Generated by Django 3.2.9 on 2022-02-14 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0003_editor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Editor',
        ),
    ]
