# Generated by Django 3.2.9 on 2022-03-08 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Group',
        ),
    ]
